spring:
  application:
    name: platform-monitor
  datasource:
    url: jdbc:mysql://localhost:3306/zuul?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 200
      max-idle: 8
      min-idle: 8
      initial-size: 10
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 5000

server:
  port: 9100

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.hostname:localhost}:${eureka.port:8761}/eureka/











